backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: "/"   # ajuste si besoin

collections:
  - name: "posts"
    label: "Articles"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Cat√©gories", name: "categories", widget: "list", allow_add: true, summary: "{{fields.item}}", hint: "Ex: Musique, Anime, Critique" }
      - {label: "Image (pour email/RSS)", name: "image", widget: "image", required: false}
      - {label: "Contenu", name: "body", widget: "markdown"}

